name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy Backend
      run: |
        sudo su dokku
        cd
        .scripts/deploy_backend api.trp-full
