name: PuTTY Examplee

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Update putty-tools package
      run: sudo apt-get update && sudo apt-get upgrade putty-tools -y

    - name: Run PuTTY with private key
      run: |
        # Create private key file
        echo "${{ secrets.PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

        # Install PuTTY (replace with appropriate download and install commands)
        sudo apt-get install putty -y

        # Convert private key format (if needed, adjust the command accordingly)
        puttygen private_key.pem -O private -o private_key.ppk

        # Run PuTTY command using private key
        putty.exe -ssh test-staging.trp.ignishealth.com -i private_key.ppk
