name: PuTTY Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set file permissions
      run: chmod 400 PRIVATE_KEY.pem

    - name: Write private key to file
      run: echo "${{ secrets.PRIVATE_KEY }}" > PRIVATE_KEY.pem

    - name: Convert private key to PuTTY format
      run: |
        openssl rsa -in PRIVATE_KEY.pem -outform DER -out PRIVATE_KEY.der

    - name: Update putty-tools package
      run: sudo apt-get update && sudo apt-get upgrade putty-tools -y

    - name: Run PuTTY with private key
      run: putty.exe -ssh username@hostname -i PRIVATE_KEY.ppk
