name: Run UI Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install dependencies and browsers
      run: |
        pip install pytest-playwright pytest-xdist pytest-html
        python -m playwright install --with-deps
    - name: Run your tests
      # first we need to go to the playwright tests directory and run pytest there to avoid
      # it auto-discovering the conftest.py for the unit tests.
      # Next, we will run the admin login test and store login state in a file
      # Then, in each test we will load the admin login state to avoid having to log in
      # inside each test.
      run: |
        cd functionality_test
        pytest --base-url https://test-staging.trp.ignishealth.com --headed -nauto --html=report.html .\functionality_test\test_applying_date_time_filter_days_of_week.py
        
    - name: List files in the specified directory
      run:  ls -R Playwright/functionality_test

    - name: Upload HTML report
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: report.html
