name: Run Vagrant

on:
  push:
    branches:
      - main

jobs:
  vagrant:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Vagrant and VirtualBox
      run: |
        sudo apt-get update
        sudo apt-get install vagrant virtualbox -y
      if: runner.os == 'Linux' # Adjust for other OS runners

    - name: Provision Vagrant VM
      run: vagrant up

    - name: SSH into Vagrant VM and run commands
      run: |
        vagrant ssh -c "echo 'Running commands on Vagrant VM'"
        vagrant ssh -c "your-command-here" # Replace with your actual commands

    - name: Halt and destroy Vagrant VM
      run: vagrant halt && vagrant destroy -f
